apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: pirafrank/flaskapp:1.0.0
        ports:
          - containerPort: 5000
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.25"
