apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flaskapp-rollout
  labels:
    app: flaskapp
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: pirafrank/flaskapp:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.25"
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: flaskapp-service
      previewService: flaskapp-service-preview
